service: node-serverless
stage: dev
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: server.start
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
